#!/bin/bash

logs() {
    echo -e "`date +%Y-%m-%d\ %H:%M:%S `\033[32m $@ \033[0m"
    sleep 1
    return 0
}


err() {
    echo -e "`date +%Y-%m-%d\ %H:%M:%S `\033[31m $@ \033[0m"
    sleep 1
    return 1
}
